spring.datasource.url=jdbc:h2:mem:midasdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=create-drop

spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.auto-offset-reset=earliest
general.kafka-topic=midas-topic



logging.level.root=INFO
logging.level.org.apache.kafka=WARN
logging.level.org.springframework=WARN
logging.level.org.hibernate=WARN